from enum import Enum

class ErrorCodes(Enum):
    INVALID_CUSTOMER_DOCUMENT = "INVALID_CUSTOMER_DOCUMENT"
    INVALID_PRODUCT_TYPE = "INVALID_PRODUCT_TYPE"
    INVALID_SOLD_AT = "INVALID_SOLD_AT"
    INVALID_TOTAL = "INVALID_TOTAL"
    CASHBACK_ERROR = "CASHBACK_ERROR"
    UNDEFINED_ERROR = "UNDEFINED_ERROR"
    
class SuccessCodes(Enum):
    SUCCESS = 'SUCCESS'
